Monorepo and find-language readmes
sillsdev/EthnoLib pull request #15
Opened 2024-10-09 00:03 UTC by nabalone

2024-10-09 00:04 UTC, nabalone commented on components/language-chooser/common/find-language/README.md
> +<!-- TODO move to usage section? -->
Not sure which section Search Result Modification should go in

2024-10-09 00:05 UTC, nabalone commented
Ready for review. Still some TODOs/sections to fill in but ready for feedback

2024-10-09 15:22 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/15)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`components/language-chooser/common/find-language/README.md` line 14 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/15#gh-1792633742:-O8lpRFk0a1lmu4ER2Ui:b-sagspi) ([raw file](https://github.com/sillsdev/EthnoLib/blob/0ab58e3ca5092055cd51fcc0e0cebeccc81dad1a/components/language-chooser/common/find-language/README.md#L14)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Not sure which section Search Result Modification should go in
</blockquote></details>

Probably usage. Thanks.


<!-- Sent from Reviewable.io -->

2024-10-09 21:43 UTC, andrew-polk requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/15)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2024-10-10 20:40 UTC, nabalone commented on components/language-chooser/common/find-language/scripts.json
This file is unused and was in the repo by mistake

2024-10-10 20:41 UTC, nabalone commented
Ready for review

2024-10-10 21:21 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/15)* status: 1 of 14 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`components/language-chooser/common/find-language/README.md` line 14 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/15#gh-1792633742:-O8sIfIL7CTE_AA0nDIw:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/0ab58e3ca5092055cd51fcc0e0cebeccc81dad1a/components/language-chooser/common/find-language/README.md#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably usage. Thanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-11 15:47 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/15)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-10-11 15:48 UTC, merged